dependencies:
  # - <organization/repo>@version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env
networks:
  default: development
  kovan:
    eth_usd_price_feed: '0x5d62EcdF66E18d7dB0161a62049Cb7542ce4e15E'
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

wallets:
  from_key: ${PRIVATE_KEY}